import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { Inter } from 'next/font/google'
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/theme-toggle";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar"
import Footer from "@/components/Footer";
import Nav from "@/components/Nav";
import { verifySession } from "@/lib/dal";



const inter = Inter({
  subsets: ['latin'],
  display: 'swap'
})


// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const isAuth = await verifySession()




  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased`}
      >{
          isAuth ? (
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <ThemeToggle />
              <SidebarProvider>
                <AppSidebar />
                <Nav />
                <main>
                  <SidebarTrigger />
                  {children}
                </main>
                <Footer />
              </SidebarProvider>
            </ThemeProvider>
          ) : (
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <ThemeToggle />
              <Nav />
              <main>
                {children}
              </main>
              <Footer />
            </ThemeProvider>
          )
        }

      </body>
    </html>
  );
}
